### ISSUE TITLE
Extension to analyze 5D-Ricci-Flatness (Rij = 0)

### ISSUE THREAD

**Issue by DetlefHoyer** [NerdsWithAttitudes/WarpFactory#3]
An extension to view 5D-Ricci-Flatness (Rik = 0) is needed to view the negative energy of the scalar field (Kaluza-Theory), 
which cancels the electrostatic field energy of a charge with mass. As the gravitational field of a mass has no field energy,
the over all energy distrubution in 4D and 5D has to be a zero-field.
[(electric) ... monopole ... and the role of negative scalar field energy in vacuum solutions](https://iopscience.iop.org/article/10.1088/2399-6528/ac4461) (2.3 eq. 16)
Next steps would be: analyzing the energies of a moving charge (has field energy E x B), comparison of 4D and 5D Reissner-Nordström solutuions.
If granted, i can write the code for it (after some time).

**Comment by pbbp0904** [comment]
Integrating Kaluza theory into Warp Factory would probably take moderate rearchitecting of at least all of the solver functions.
Feel free to fork the repo though! If you let me know, I can add it as a highlighted fork in the readme.
